"""add longitude and latitude to users and vet

Revision ID: 35c22c485792
Revises: a87f44083b09
Create Date: 2023-12-10 01:24:38.005413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c22c485792'
down_revision: Union[str, None] = 'a87f44083b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vets', 'longitude')
    op.drop_column('vets', 'latitude')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    # ### end Alembic commands ###
