"""add column to vets and dogs

Revision ID: 5a883dc9d868
Revises: a9597dd47d05
Create Date: 2023-12-13 15:18:43.036853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a883dc9d868'
down_revision: Union[str, None] = 'a9597dd47d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('microchip_id', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('email', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('start_work_hour', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('end_work_hour', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('vets', sa.Column('education', sa.String(), nullable=True))
    op.alter_column('vets', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vets', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('vets', 'education')
    op.drop_column('vets', 'experience')
    op.drop_column('vets', 'end_work_hour')
    op.drop_column('vets', 'start_work_hour')
    op.drop_column('vets', 'email')
    op.drop_column('dogs', 'microchip_id')
    # ### end Alembic commands ###
