"""add image column to vet table

Revision ID: a87f44083b09
Revises: eb5952eff5ea
Create Date: 2023-11-29 09:22:46.229602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87f44083b09'
down_revision: Union[str, None] = 'eb5952eff5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vets', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vets', 'image')
    # ### end Alembic commands ###
